//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 成本管理.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xm_plug_t_materialUnitPice
    {
        public int ID { get; set; }
        public string FID { get; set; }
        public string cinvCode { get; set; }
        public double unitPrice { get; set; }
    }
}
