//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 成本管理.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH001_0001_E001
    {
        public string cNo { get; set; }
        public string cMaker { get; set; }
        public Nullable<System.DateTime> dMakeDateEx { get; set; }
        public Nullable<System.DateTime> dMakeDate { get; set; }
        public string cMender { get; set; }
        public Nullable<System.DateTime> dModifyDateEx { get; set; }
        public Nullable<System.DateTime> dModifyDate { get; set; }
        public string cAuditor { get; set; }
        public Nullable<System.DateTime> dAuditDateEx { get; set; }
        public Nullable<System.DateTime> dAuditDate { get; set; }
        public string CH001_0001_E001_F010 { get; set; }
        public string CH001_0001_E001_F011 { get; set; }
        public int CH001_0001_E001_PK { get; set; }
        public Nullable<int> iswfcontrolled { get; set; }
        public Nullable<int> iverifystate { get; set; }
        public Nullable<int> ireturncount { get; set; }
        public Nullable<int> UAPRuntime_RowNO { get; set; }
        public string UAP_VoucherTransform_Rowkey { get; set; }
    }
}
